### ISSUE TITLE
Replace hard string "device_db.py" with `configs["device_db_path"]`

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#101]
### Feature you want to implement
When we implemented using device db file first, we set the path as the hard string "device_db.py".
For device monitor e.g., setting TTL level, however, we used the path in `configs` instead of the hard string.
Hence, I will replace all hard strings with `configs["device_db_path"]`.

It will NOT modify its behavior.

**Comment by kangz12345** [comment]
Is this still in progress? @BECATRUE

**Comment by BECATRUE** [comment]
Oh, I already resolved it in #76. Hence, I close this issue.
