### ISSUE TITLE
Replace subscribing mechanism with web socket

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#112]
### Feature you want to implement
As discussed in #105, we will replace subscribing mechanism e.g., fetching schedule and dataset with web socket.

- Fetching schedule
#113 
- Fetching dataset
#115 

If you aren't familiar to web socket, please refer to [FastAPI](https://fastapi.tiangolo.com/advanced/websockets/).

**Comment by kangz12345** [comment]
I close this as it looks it is done. Please reopen it if it is not.
