### ISSUE TITLE
Synchronize TTL status

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#119]
### Feature you want to implement
I will implement to synchronize TTL status, i.e., whether overriding and level are on or off.
In addition, I will support to turn on or off all TTLs.

#### Synchronize TTL status
- Once the server is started, a `CommMonInj` connection is established and monitoring `TTLProbe.level.value`, `TTLOverride.en.value`, and  `TTLOverride.level.value` is started.
- Once its callback function is called, an asyncio event corresponding to each TTL monitoring signal is set.
- This is connected to an IQUIP client by a websocket, and it waits the asyncio events above.
- Once it wakes up, it sends the modification to the IQUIP client.
- ~~To know the status of the first connection, I will use a trick: After the connection is made, a short time later, through [get_injection_status()](https://github.com/m-labs/artiq/blob/master/artiq/coredevice/comm_moninj.py#L77) the callback function is called. It may have the initial information.~~
- To know the status of the first connection, once the connection is established, it sends the current value.

#### Turn on or off all TTLs
- Implement `async def set_all_ttl_levels(value: bool)` similar to `set_ttl_level()`.

**Comment by kangz12345** [comment]
Is `set_all_ttl_levels(value: bool)` actually what we want? I thought something more like "presets", which sets multiple TTL levels simultaneously (e.g., turn on the cooling beam, MW, shutter and turn off the others).

**Comment by BECATRUE** [comment]
> Is `set_all_ttl_levels(value: bool)` actually what we want? I thought something more like "presets", which sets multiple TTL levels simultaneously (e.g., turn on the cooling beam, MW, shutter and turn off the others).

As we discussed, I will remove this feature and plan a feature like "presets" later.

**Comment by BECATRUE** [comment]
I made a new issue based on what was discussed in #120, so I close this issue.
