### ISSUE TITLE
Get current status of a specific experiment

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#121]
### Feature you want to implement
I will implement to get current status of a specific experiment.
It is only used by only snu-quiqcl/artiq-qiskit#2 for now, but it can be used in various places.

### How the feature is implemented
- It returns `remote.get_status()[rid]`. Hence, if the given experiment is done or cancelled, it returns `None`.

### Additional context
As I searched, there is no way to distinguish an experiment with an error from a done experiment...

**Comment by kangz12345** [comment]
We would be able design the artiq experiment for qiskit circuit execution to distinguish errors, so let's do not care of that issue.
