### ISSUE TITLE
Support `Scannable` arguments

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/artiq-proxy#144]
### Feature you want to implement
Now `iquip` supports `Scannable` arguments, so let's implement that feature in `artiq-proxy` as well.

### How the feature is implemented
Modify the experiment submission part.

**Comment by BECATRUE** [comment]
@kangz12345 

We don't need to update `artiq-proxy`, because a scannable argument is handled as just a certain build argument and we already send the scannable argument to meet the condition in `artiq-master`.
In other words, this feature is already supported.

**Comment by BECATRUE** [comment]
In addition, I tested if scannable arguments work well in my local `artiq-master` and `artiq-proxy` enviroment.

**Comment by kangz12345** [comment]
Oh, then could you provide an example experiment code?

**Comment by kangz12345** [comment]
As @BECATRUE said, `artiq-proxy` is not responsible for this.

FYI:
The scan objects are not iterable in kernels, so one should `list`-ify the scan object in a host function, e.g., `prepare()`.
