### ISSUE TITLE
Experiment queue fetcher for display in `iquip/apps/scheduler.py`

### ISSUE THREAD

**Issue by giwon2004** [snu-quiqcl/artiq-proxy#29]
### Feature you want to implement
From `artiq_master`, the experiment queue is returned when `$ artiq_client show schedule`.
Here, it is again implemented in `main.py` to fetch this information and send it to `scheduler.py` to display the queued experiments.

**Comment by BECATRUE** [comment]
Do you have any plan how to fetch the scheduled queue?

I think you should request it periodically, so that I'm worried that it makes the server too busy.

**Comment by giwon2004** [comment]
I am thinking about posting the information when an experiment is newly added to the queue, started to run a queued experiment, etc., while the thread that receives this information is held inside the `scheduler.py` to reduce the server load.

**Comment by BECATRUE** [comment]
Then, how can it detect when a new experiment starts?

**Comment by kangz12345** [comment]
See also: snu-quiqcl/iquip#90

**Comment by giwon2004** [comment]
See also: https://github.com/snu-quiqcl/iquip/discussions/94
