### ISSUE TITLE
Release v1.1.1

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/artiq-proxy#30]
Now all the planned features for v1.1.1 are implemented. Let's release it!

**Comment by BECATRUE** [comment]
I relaesed the newer version!
Please check it and if no problem, close this issue. @kangz12345

**Comment by kangz12345** [comment]
I found that the "What's changed" logs are accumulated and there are so many duplicate change logs (note that v1.1.1 must have only one change log).
So we have to select the previous tag (v1.1.0) manually and then click the generate button.

**Comment by kangz12345** [comment]
@BECATRUE After you read this, you can close the issue.

**Comment by BECATRUE** [comment]
Oh, I've only checked it now😅

I will modify the release.

**Comment by BECATRUE** [comment]
Oh, you already fixed it, right?

**Comment by kangz12345** [comment]
Yes I fixed it :) I will close this issue.
