### ISSUE TITLE
Save the submission information

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#42]
### Feature you want to implement
- If the visualize option is set, save the submission information in the corresponding directory, i.e., `${master_path}/{visualize_path}/{RID}/`.

### How the feature is implemented
- Save all information to `metadata.json`.
- The information is as follows:
  - Submission time

**Comment by kangz12345** [comment]
How about "metadata" instead of "info"?

**Comment by kangz12345** [comment]
In addition, please determine what values will be included, just before you start implementation.

**Comment by BECATRUE** [comment]
> In addition, please determine what values will be included, just before you start implementation.

I updated it!

**Comment by BECATRUE** [comment]
As @kangz12345 and I discussed offline, we decided to save only the submission time.

Also, this issue looks simple, so I will implement this with #37.
