### ISSUE TITLE
Make a replica of a `Scheduler` class that delivers all function call request to the artiq server

### ISSUE THREAD

**Issue by giwon2004** [snu-quiqcl/artiq-proxy#44]
### Feature you want to implement
As mentioned in [Issue#96](https://github.com/snu-quiqcl/iquip/issues/96) of `iquip`, I need a port to send the modify request of the queued experiment to the _real_ scheduler in the server.

### How the feature is implemented
In `main.py`, I will make a POST (maybe GET if it needs return value) request path that receives a function call request of functions in [`artiq/artiq/master/scheduler.py`](https://github.com/m-labs/artiq/blob/master/artiq/master/scheduler.py#L400) and calls the functions in scheduler that is connected by `remote = get_client("master_schedule")`.

**Comment by kangz12345** [comment]
You can mention an issue in another repo like: snu-quiqcl/iquip#96.

**Comment by giwon2004** [comment]
> You can mention an issue in another repo like: [snu-quiqcl/iquip#96](https://github.com/snu-quiqcl/iquip/issues/96).

Oh, okay. I will use that from now on!
