### ISSUE TITLE
Fetch experiment only when updated using `Subscriber`

### ISSUE THREAD

**Issue by giwon2004** [snu-quiqcl/artiq-proxy#51]
### Feature you want to implement
By PR #41, the [code](https://github.com/snu-quiqcl/artiq-proxy/blob/develop/main.py#L116)
```
    while current_queue == previous_queue:
        await asyncio.sleep(0)
        current_queue.clear()
        current_queue.update(remote.get_status())
```
is added, where it calls `remote.get_status()` repeatedly without delay.

As the `remote` is a server element, making too frequent requests will not be a good way to implement a fetcher.

### How the feature is implemented
Using [`Subscriber`](https://github.com/m-labs/sipyco/blob/master/sipyco/sync_struct.py#L174) class can detect changes and it calls functions that I preselected (by `notify_cb`) to inform update detection. I can set the function to change [`current_queue`](https://github.com/snu-quiqcl/artiq-proxy/blob/develop/main.py#L119) value via `Subscriber`.

### Blockers
However, I am not sure whether `Subscriber` works with `remote.get_status()` or not. If not, I need to make use of a different way rather than using `remote` to implement this.

**Comment by kangz12345** [comment]
#112 resolved this.
