### ISSUE TITLE
Save RIDs under a subdirectory temporarily

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#60]
> As we discussed offline, please create an issue for using a subdirectory instead of the prefix "_" and ignore this review comment in this PR.

_Originally posted by @kangz12345 in https://github.com/snu-quiqcl/artiq-proxy/pull/59#discussion_r1320987861_

**Comment by kangz12345** [comment]
As we decided not to rearrange the result files, I closed the issue.
See also #123
