### ISSUE TITLE
Queue is not fetched

### ISSUE THREAD

**Issue by giwon2004** [snu-quiqcl/artiq-proxy#61]
See [iquip #136](https://github.com/snu-quiqcl/iquip/issues/136).

Are there any expected causes of halt of `main.py`?

**Comment by BECATRUE** [comment]
I just realized this issue, but I don't know the exact reason yet😅

**Comment by BECATRUE** [comment]
As I tested with `curl -X GET 'http://127.0.0.1:8000/experiment/queue/'`, there is no problem to fetch the scheduled queue.
Hence I think this problem is caused by IQUIP, not the proxy server.

**Comment by BECATRUE** [comment]
I updated fetching mechanism in #85 and resolved this issue.
