### ISSUE TITLE
Pass the unittest without any error

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#63]
### Feature you want to implement
As I understood, after merging #50, the unittests have failed since it modified the submission part, but the corresponding unittest wasn't updated.
So I will resolve this unittest errors.

**Comment by BECATRUE** [comment]
@kangz12345 

I tried to resolve this error, but I realized that the submission function, `submit_experiment` is too complicated, so it may takes a long time to do this.
But I think it is more important to develop IQUIP e.g., result visualizer or device monitor.

So how about disable the unittest in terms of `submit_experiment` through comments temporarily?

**Comment by kangz12345** [comment]
Okay then, let's postpone this and [`skip()`](https://docs.python.org/3/library/unittest.html#unittest.skip) the `test_submit_experiment()`.
Refer to the [documentation](https://docs.python.org/3/library/unittest.html#skipping-tests-and-expected-failures) for example usage.
