### ISSUE TITLE
Set the override and level option of a specific TTL

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#66]
_(updated)_

### Feature you want to implement
To control ARTIQ hardwares manually not through an experiment, we should be able to set the value of a specific TTL explicitly.
For this, in ARTIQ the function in terms of override and level is implemented in [moninj.py](https://github.com/m-labs/artiq/blob/master/artiq/dashboard/moninj.py#L701).

Similar to this, I will implement setting the override and level option of a specific TTL.

#### config.json
To limit the TTLs that users can control, a list, `ttl_channels` will be added to `config.json`.
Only TTL channel in `ttl_channels` can be overridden or controlled manually.

#### main.py
When receiving a request with the url, `~/ttl/level/?channel={channel}&value={value}`, it will set the level of the TTL channel `channel` to `value`.
When receiving a request with the url, `~/ttl/override/?value={value}`, it will set the override of all TTLs described in `config.json` to `value`.

**Comment by kangz12345** [comment]
Oh, I thought the nickname-channel dict is for the GUI client side.
In that way, the GUI can show only the channels in the dict.

**Comment by BECATRUE** [comment]
I see! Then, I will use the channel number explicitly in ARTIQ-PROXY.
