### ISSUE TITLE
Use TTL name instead of channel number as HTTP parameter

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/artiq-proxy#68]
Currently, we use a channel number, e.g., an integer to set the override and level of a specific TTL.
However it may be difficult to set `ttlInfo` in IQUIP configuration file if we have a number of TTLs because we should know what is the channel number of the specific TTL.

So I think using TTL name i.e., "ttl0", "led0" is more convenient for users.

Sure, I will do this after the first version of the device controller is done since it is more urgent.

**Comment by BECATRUE** [comment]
What do you think of this? @kangz12345

**Comment by kangz12345** [comment]
Good idea! They are the names in the device db, right?

**Comment by BECATRUE** [comment]
Correct! I will use names defined as a key in `device_db` dict.

**Comment by BECATRUE** [comment]
We decided to apply this issue, so I closed this.
