### ISSUE TITLE
Read the broadcast datasets

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/artiq-proxy#70]
### Feature you want to implement
Fetch the datasets that are broadcast to artiq master.

### How the feature is implemented
Artiq master will hold the datasets, so we will use RPC to call the getter method of the dataset DB.

### Additional context
Still investigating...

**Comment by BECATRUE** [comment]
In "artiq_client.py", showing the current dataset is implemented in [here](https://github.com/m-labs/artiq/blob/master/artiq/frontend/artiq_client.py#L335) using `Subscriber`.

**Comment by kangz12345** [comment]
Thank you for your help!
