### ISSUE TITLE
Use `Subscriber` to _watch_ dataset modifications and provide dataset fetching API

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/artiq-proxy#87]
### Feature you want to implement
The proxy server will watch all the broadcast dataset modifications and keep it in its own data structure.
New API will be introduced:
- Get currently available dataset names
- Get modifications on a specific dataset since specific time stamp

### How the feature is implemented
As I tested, `Subscriber`'s `notify_cb()` is called with an argument `mod`.
`mod` is a `dict` with keys "action", "path", "x", "i", etc.
For example, when we call `append_to_dataset("name", value)`, then `mod={"action": "append", "path": ["name", 1], "x": value}`. (I'm not sure what the `1` in `"path"` is.)

Using this information, the `artiq-proxy` server will manage a dictionary (key=dataset_name, value=modification_list).
In addition, each modification is saved with its modified time stamp.

Furthermore, since the datasets can be reset, we should save the last-reset time stamps as well.
Imagine the case where a user requested modifications before and after the dataset is reset.

**Comment by BECATRUE** [comment]
You may already know, but I think it'll help, so leave it.
In [sipyco.sync_struct](https://github.com/m-labs/sipyco/blob/master/sipyco/sync_struct.py), the modification dictionary spec is defined.

**Comment by kangz12345** [comment]
> You may already know, but I think it'll help, so leave it.
> In [sipyco.sync_struct](https://github.com/m-labs/sipyco/blob/master/sipyco/sync_struct.py), the modification dictionary spec is defined.

That helped me a lot! I did not read it thoroughly before. Thanks 👍
